In [5]:
import numpy as np

a=np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
d=np.array([[[1,4,6],[5,7,2]],
            [[5,6,7],[7,9,7]]])
print(d)
            

[[[1 4 6]
  [5 7 2]]

 [[5 6 7]
  [7 9 7]]]


In [9]:
e=np.array([['santhosh'],['kumar']])
print(e)

[['santhosh']
 ['kumar']]


In [10]:
arr=np.zeros([3,4])
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
arr=np.ones([2,3])
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:

arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
arr=np.array([[1,2,3],
[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [24]:
print(arr.shape)

(2, 3)


In [25]:
print(arr.ndim)

2


In [26]:
print(arr.size)

6


In [27]:
print(arr.dtype)

int64


In [34]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


In [35]:
print(arr[-1])

40


In [38]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [39]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [40]:
print(arr[:3])

[10 20 30]


In [41]:
print(arr[3:])

[40 50 60]


In [42]:
print(arr[::2])

[10 30 50]


In [45]:
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [47]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [49]:
arr=np.array([[1,2],
              [3,4]])
print(arr.flatten())

[1 2 3 4]


In [4]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [5]:
print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


In [6]:
arr=np.array([10,20,30,40,50])
print(np.sum(arr))

150


In [7]:
print(np.mean(arr))

30.0


In [8]:
print(np.min(arr))
print(np.max(arr))

10
50


In [9]:
print(np.std(arr))

14.142135623730951


In [1]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.size)
print(arr.dtype)

(10,)
10
int64


In [2]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
print(arr[0])

[1. 0. 0.]


In [11]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr[:10])
print(arr[-5:])
print(arr[6:10])

[ 1  2  3  4  5  6  7  8  9 10]
[16 17 18 19 20]
[ 7  8  9 10]


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
new_arr=arr.reshape(2,6)
print(new_arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
